services:
  - type: web
    name: whatsapp-birthday-buddy
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /opt/render/project/src/database/birthday.db
      - key: BOT_PREFIX
        value: "@smartbot"
      - key: OWNER_NUMBER
        sync: false
    disk:
      name: database
      mountPath: /opt/render/project/src/database
      sizeGB: 1
